In [0]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
gsr=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Training_Data.csv')

In [0]:
gsr_val=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Test_May_10.csv')

gsr.head(5)

In [0]:
gsr.shape

(20000, 135)

In [0]:
gsr=gsr.apply(lambda x: x.fillna(x.median()))

In [0]:
gsr_val=gsr_val.apply(lambda x: x.fillna(x.median())) 

In [0]:
gsr_val.shape

(5000, 137)

In [0]:
x_val1=gsr_val[['5yrs_sharpe_ratio_fund','10yrs_sharpe_ratio_fund','3yrs_sharpe_ratio_fund','fund_return_3years','3_years_alpha_fund','5_years_return_fund','5_years_alpha_fund','5_years_return_mean_annual_fund','10_years_alpha_fund','3_years_return_mean_annual_fund','10_years_return_fund','10_years_return_mean_annual_fund','1_year_return_fund','2015_return_fund','2014_return_fund','2010_return_fund','2012_fund_return','2018_return_fund','2011_return_fund','2017_return_fund','years_up','10yrs_sharpe_ratio_category','1_month_fund_return','fund_return_3months','return_ytd','ytd_return_fund','total_assets','2016_return_fund','investment_class_Growth','2010_return_category','maturity_bond','yield','ID-20 and older','portfolio_tech_allocation','mmc','ID-10 to 15','5yrs_sharpe_ratio_category','ID-0 to 5 years','5years_fund_std','3years_fund_std','10years_fund_std','2012_return_category','10_years_return_category','fund_beta_3years','ID-5 to 10','a_rating','pb_ratio','2013_return_fund','2014_category_return','ytd_return_category','3_months_return_category','category_return_1year','category_return_1month','2017_category_return','2016_return_category']]

In [0]:
print(x_val1.shape)
x_val1_scaled = preprocessing.scale(x_val1)

(5000, 55)


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [0]:
x1=gsr[['5yrs_sharpe_ratio_fund','10yrs_sharpe_ratio_fund','3yrs_sharpe_ratio_fund','fund_return_3years','3_years_alpha_fund','5_years_return_fund','5_years_alpha_fund','5_years_return_mean_annual_fund','10_years_alpha_fund','3_years_return_mean_annual_fund','10_years_return_fund','10_years_return_mean_annual_fund','1_year_return_fund','2015_return_fund','2014_return_fund','2010_return_fund','2012_fund_return','2018_return_fund','2011_return_fund','2017_return_fund','years_up','10yrs_sharpe_ratio_category','1_month_fund_return','fund_return_3months','return_ytd','ytd_return_fund','total_assets','2016_return_fund','investment_class_Growth','2010_return_category','maturity_bond','yield','ID-20 and older','portfolio_tech_allocation','mmc','ID-10 to 15','5yrs_sharpe_ratio_category','ID-0 to 5 years','5years_fund_std','3years_fund_std','10years_fund_std','2012_return_category','10_years_return_category','fund_beta_3years','ID-5 to 10','a_rating','pb_ratio','2013_return_fund','2014_category_return','ytd_return_category','3_months_return_category','category_return_1year','category_return_1month','2017_category_return','2016_return_category']]

In [0]:
print(x1.shape)
x1_scaled = preprocessing.scale(x1)

(20000, 55)


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [0]:
y=gsr[['greatstone_rating_0','greatstone_rating_1','greatstone_rating_2','greatstone_rating_3','greatstone_rating_4','greatstone_rating_5']]

In [0]:
y_all=gsr['greatstone_rating']

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import f1_score,classification_report, confusion_matrix,accuracy_score
clf=RandomForestClassifier( n_jobs=9999,n_estimators=9999,criterion="entropy",random_state=999)
#clf3=RandomForestClassifier( n_jobs=9999,n_estimators=9999,criterion="entropy",random_state=999)

In [0]:
clf.fit(x1, y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=9999,
                       n_jobs=9999, oob_score=False, random_state=999,
                       verbose=0, warm_start=False)

In [0]:
y_predict_val1 = clf.predict(x_val1)

In [0]:
y_predict_val_exp1=pd.DataFrame(y_predict_val1)

In [0]:
y_predict_val_exp1.to_excel('/content/drive/My Drive/Colab Notebooks/y_predict_Rating_1st_Run.xlsx')

In [0]:
gsr1=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Training_Data_1.csv')

In [0]:
gsr1.shape

(24045, 135)

In [0]:
gsr1=gsr1.apply(lambda x: x.fillna(x.mean()))

In [0]:
x2=gsr1[['5yrs_sharpe_ratio_fund','10yrs_sharpe_ratio_fund','3yrs_sharpe_ratio_fund','fund_return_3years','3_years_alpha_fund','5_years_return_fund','5_years_alpha_fund','5_years_return_mean_annual_fund','10_years_alpha_fund','3_years_return_mean_annual_fund','10_years_return_fund','10_years_return_mean_annual_fund','1_year_return_fund','2015_return_fund','2014_return_fund','2010_return_fund','2012_fund_return','2018_return_fund','2011_return_fund','2017_return_fund','years_up','10yrs_sharpe_ratio_category','1_month_fund_return','fund_return_3months','return_ytd','ytd_return_fund','total_assets','2016_return_fund','investment_class_Growth','2010_return_category','maturity_bond','yield','ID-20 and older','portfolio_tech_allocation','mmc','ID-10 to 15','5yrs_sharpe_ratio_category','ID-0 to 5 years','5years_fund_std','3years_fund_std','10years_fund_std','2012_return_category','10_years_return_category','fund_beta_3years','ID-5 to 10','a_rating','pb_ratio','2013_return_fund','2014_category_return','ytd_return_category','3_months_return_category','category_return_1year','category_return_1month','2017_category_return','2016_return_category']]

In [0]:
x2.shape

(24045, 55)

In [0]:
y1=gsr1[['greatstone_rating_0','greatstone_rating_1','greatstone_rating_2','greatstone_rating_3','greatstone_rating_4','greatstone_rating_5']]

In [0]:
y1_all=gsr1['greatstone_rating']

In [0]:
clf.fit(x2, y1)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=9999,
                       n_jobs=9999, oob_score=False, random_state=999,
                       verbose=0, warm_start=False)

In [0]:
y_predict_val2 = clf.predict(x_val1)

In [0]:
y_predict_val_exp2=pd.DataFrame(y_predict_val2)

In [0]:
y_predict_val_exp2.to_excel('/content/drive/My Drive/Colab Notebooks/y_predict_Rating_2nd_Run.xlsx')

In [0]:
gsr2=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Training_Data_2.csv')

In [0]:
gsr2.shape

(24177, 135)

In [0]:
gsr2=gsr2.apply(lambda x: x.fillna(x.mean()))

In [0]:
x3=gsr2[['5yrs_sharpe_ratio_fund','10yrs_sharpe_ratio_fund','3yrs_sharpe_ratio_fund','fund_return_3years','3_years_alpha_fund','5_years_return_fund','5_years_alpha_fund','5_years_return_mean_annual_fund','10_years_alpha_fund','3_years_return_mean_annual_fund','10_years_return_fund','10_years_return_mean_annual_fund','1_year_return_fund','2015_return_fund','2014_return_fund','2010_return_fund','2012_fund_return','2018_return_fund','2011_return_fund','2017_return_fund','years_up','10yrs_sharpe_ratio_category','1_month_fund_return','fund_return_3months','return_ytd','ytd_return_fund','total_assets','2016_return_fund','investment_class_Growth','2010_return_category','maturity_bond','yield','ID-20 and older','portfolio_tech_allocation','mmc','ID-10 to 15','5yrs_sharpe_ratio_category','ID-0 to 5 years','5years_fund_std','3years_fund_std','10years_fund_std','2012_return_category','10_years_return_category','fund_beta_3years','ID-5 to 10','a_rating','pb_ratio','2013_return_fund','2014_category_return','ytd_return_category','3_months_return_category','category_return_1year','category_return_1month','2017_category_return','2016_return_category']]

In [0]:
x3.shape

(24177, 55)

In [0]:
y2=gsr2[['greatstone_rating_0','greatstone_rating_1','greatstone_rating_2','greatstone_rating_3','greatstone_rating_4','greatstone_rating_5']]

In [0]:
y2_all=gsr2['greatstone_rating']

In [0]:
clf.fit(x3, y2)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=9999,
                       n_jobs=9999, oob_score=False, random_state=999,
                       verbose=0, warm_start=False)

In [0]:
y_predict_val3 = clf.predict(x_val1)

In [0]:
y_predict_val_exp3=pd.DataFrame(y_predict_val3)

In [0]:
y_predict_val_exp3.to_excel('/content/drive/My Drive/Colab Notebooks/y_predict_Rating_3rd_Run.xlsx')

In [0]:
gsr3=pd.read_csv('/content/drive/My Drive/Colab Notebooks/Training_Data_97.csv')

In [0]:
gsr3.shape

(24979, 135)

In [0]:
gsr3=gsr3.apply(lambda x: x.fillna(x.mean()))

In [0]:
x4=gsr3[['5yrs_sharpe_ratio_fund','10yrs_sharpe_ratio_fund','3yrs_sharpe_ratio_fund','fund_return_3years','3_years_alpha_fund','5_years_return_fund','5_years_alpha_fund','5_years_return_mean_annual_fund','10_years_alpha_fund','3_years_return_mean_annual_fund','10_years_return_fund','10_years_return_mean_annual_fund','1_year_return_fund','2015_return_fund','2014_return_fund','2010_return_fund','2012_fund_return','2018_return_fund','2011_return_fund','2017_return_fund','years_up','10yrs_sharpe_ratio_category','1_month_fund_return','fund_return_3months','return_ytd','ytd_return_fund','total_assets','2016_return_fund','investment_class_Growth','2010_return_category','maturity_bond','yield','ID-20 and older','portfolio_tech_allocation','mmc','ID-10 to 15','5yrs_sharpe_ratio_category','ID-0 to 5 years','5years_fund_std','3years_fund_std','10years_fund_std','2012_return_category','10_years_return_category','fund_beta_3years','ID-5 to 10','a_rating','pb_ratio','2013_return_fund','2014_category_return','ytd_return_category','3_months_return_category','category_return_1year','category_return_1month','2017_category_return','2016_return_category']]

In [0]:
x4.shape

(24979, 55)

In [0]:
y3=gsr3[['greatstone_rating_0','greatstone_rating_1','greatstone_rating_2','greatstone_rating_3','greatstone_rating_4','greatstone_rating_5']]

In [0]:
y3_all=gsr3['greatstone_rating']

In [0]:
clf.fit(x4, y3)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=9999,
                       n_jobs=9999, oob_score=False, random_state=999,
                       verbose=0, warm_start=False)

In [0]:
y_predict_val3 = clf.predict(x_val1)

In [0]:
y_predict_val_exp3=pd.DataFrame(y_predict_val3)

In [0]:
y_predict_val_exp3.to_excel('/content/drive/My Drive/Colab Notebooks/y_predict_Rating_97.xlsx')

In [0]:
clf.fit(x4, y3_all)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=9999,
                       n_jobs=9999, oob_score=False, random_state=999,
                       verbose=0, warm_start=False)

In [0]:
y_predict_val5 = clf.predict(x_val1)

In [0]:
y_predict_val_exp5=pd.DataFrame(y_predict_val5)

In [0]:
y_predict_val_exp5.to_excel('/content/drive/My Drive/Colab Notebooks/y_predict_Rating_Final.xlsx')

Using Other models

1. Logistic Regression

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
LR = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr')

In [0]:
y0=gsr['greatstone_rating_0']

In [0]:
LR.fit(x2,y0)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=0,
                   solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

In [0]:
y0_val=LR.predict(x_val)

In [0]:
y_predict_val_exp0=pd.DataFrame(y0_val)

In [0]:
y_predict_val_exp0.to_excel('/content/drive/My Drive/Colab Notebooks/y_val_0.xlsx')

In [0]:
x_train_scaled = preprocessing.scale(x_train2)
x_test_scaled = preprocessing.scale(x_test2)
clf3.fit(x_train_scaled, y_train)
y_predict = clf3.predict(x_test_scaled)
#model_score = clf.score(x_test_scaled, y_test)
print(metrics.confusion_matrix(y_test, y_predict))
print(metrics.accuracy_score(y_test, y_predict))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


[[ 378    2    6    1    0    1]
 [   1  206  159   43    4    0]
 [   0   40  883  318   15    2]
 [   0    6  170 1663  196    8]
 [   2    0   28  376  966   56]
 [   0    0    4   42  142  282]]
0.7296666666666667


In [0]:
x_train_scaled = preprocessing.scale(x_train)
x_test_scaled = preprocessing.scale(x_test)
clf.fit(x_train, y_train)
y_predict = clf.predict(x_test)
#model_score = clf.score(x_test_scaled, y_test)
print(metrics.confusion_matrix(y_test, y_predict))
print(metrics.accuracy_score(y_test, y_predict))

C:\Users\Faisal\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:172: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
C:\Users\Faisal\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:172: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


[[ 384    0    2    1    0    1]
 [   1  266  140    6    0    0]
 [   0   44  975  229   10    0]
 [   1    1  132 1715  191    3]
 [   1    0    8  266 1084   69]
 [   0    0    1    8  122  339]]
0.7938333333333333


In [0]:
x_train_scaled = preprocessing.scale(x_train2)
x_test_scaled = preprocessing.scale(x_test2)
clf.fit(x_train_scaled, y_train)
y_predict = clf.predict(x_test_scaled)
#model_score = clf.score(x_test_scaled, y_test)
print(metrics.confusion_matrix(y_test, y_predict))
print(metrics.accuracy_score(y_test, y_predict))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


[[ 379    1    4    2    1    1]
 [   0  240  164    9    0    0]
 [   0   32  984  232    9    1]
 [   0    2  137 1742  161    1]
 [   1    0   10  305 1058   54]
 [   0    0    1   12  137  320]]
0.7871666666666667


In [0]:
x1=gsr.drop(['greatstone_rating','tag','maturity_bond'],axis=1)

In [0]:
x_train1, x_test1, y_train, y_test = train_test_split(x1, y, test_size=0.30,random_state=1)

In [0]:
clf.fit(x_train1, y_train)
y_predict = clf.predict(x_test1)
#model_score = clf.score(x_test_scaled, y_test)
print(metrics.confusion_matrix(y_test, y_predict))
print(metrics.accuracy_score(y_test, y_predict))

[[ 384    0    2    1    0    1]
 [   1  267  138    7    0    0]
 [   0   43  975  231    9    0]
 [   1    1  131 1714  192    4]
 [   1    0    8  267 1080   72]
 [   0    0    1    7  119  343]]
0.7938333333333333


In [0]:
x2=gsr.drop(['greatstone_rating','tag','investment_class_null','inception_date','10years_category_r_squared','10years_fund_r_squared','10years_fund_std','10_years_beta_fund','10yrs_treynor_ratio_fund','10_years_return_mean_annual_category','10yrs_treynor_ratio_category','10_years_alpha_category','10_years_beta_category','10years_category_std','10_years_return_category','category_r_squared_5years','5years_fund_r_squared','5years_fund_std','5yrs_sharpe_ratio_category','5_years_beta_fund','5yrs_treynor_ratio_fund','5yrs_treynor_ratio_category','5_years_alpha_category','5_years_beta_category','5years_category_std','5_years_return_category','portfolio_communication_allocation','portfolio_financial_services','portfolio_industrials_allocation','portfolio_tech_allocation','portfolio_materials_basic_allocation','portfolio_energy_allocation','portfolio_consumer_defence_allocation','portfolio_healthcare_allocation','portfolio_property_allocation','portfolio_utils_allocation','portfolio_cyclical_consumer_allocation','3yrs_treynor_ratio_fund','3years_category_std','3yrs_treynor_ratio_category','fund_beta_3years','3years_fund_r_squared','3years_fund_std','category_beta_3years','3_years_alpha_category','3_years_return_mean_annual_category','3yrs_sharpe_ratio_category','3years_category_r_squared','3_years_return_category','fund_ratio_net_annual_expense','bb_rating','below_b_rating','others_rating','maturity_bond','b_rating','a_rating','aaa_rating','aa_rating','bbb_rating','duration_bond','cash_percent_of_portfolio','us_govt_bond_rating','fund_size_Null'],axis=1)

In [0]:
x2.head(2)

investment_class_Blend  ...  2013_category_return
0                       1  ...                 10.07
1                       1  ...                 31.50

[2 rows x 62 columns]

In [0]:
x2.shape

(20000, 62)

In [0]:
x_train2, x_test2, y_train, y_test = train_test_split(x2, y, test_size=0.30,random_state=1)

In [0]:
clf.fit(x_train2, y_train)
y_predict = clf.predict(x_test2)
#model_score = clf.score(x_test_scaled, y_test)
print(metrics.confusion_matrix(y_test, y_predict))
print(metrics.accuracy_score(y_test, y_predict))

[[ 381    1    2    3    0    1]
 [   1  256  149    7    0    0]
 [   0   39  974  235   10    0]
 [   1    3  137 1714  187    1]
 [   2    0    9  277 1073   67]
 [   0    0    1   11  120  338]]
0.7893333333333333


In [0]:
y_predict_val = clf.predict(x_val)

In [0]:
from sklearn.decomposition import PCA

pca = PCA()
x_trainnew2 = pca.fit_transform(x_train2)
x_testnew2 = pca.transform(x_test2)

In [0]:
clf.fit(x_trainnew2, y_train)
y_predict = clf.predict(x_testnew2)
#model_score = clf.score(x_test_scaled, y_test)
print(metrics.confusion_matrix(y_test, y_predict))
print(metrics.accuracy_score(y_test, y_predict))

[[ 379    0    3    4    1    1]
 [   0  190  186   37    0    0]
 [   5   32  776  431   14    0]
 [   1    1  152 1646  239    4]
 [   2    0   10  488  864   64]
 [   0    0    4   53  174  239]]
0.6823333333333333


In [0]:
clf.fit(scaledx_train2, y_train)
y_predict = clf.predict(scaledx_test2)
#model_score = clf.score(x_test_scaled, y_test)
print(metrics.confusion_matrix(y_test, y_predict))
print(metrics.accuracy_score(y_test, y_predict))

[[ 381    1    2    2    1    1]
 [   0  255  150    8    0    0]
 [   0   38  978  232   10    0]
 [   1    3  135 1715  188    1]
 [   2    0    8  277 1073   68]
 [   0    0    1   10  122  337]]
0.7898333333333334


In [0]:
x_train2['fund_size_Null'].head(2)

11408    0
3616     0
Name: fund_size_Null, dtype: int64

2. DecisionTreeClassifier


In [0]:
from sklearn.tree import DecisionTreeClassifier

In [0]:
dt_model = DecisionTreeClassifier(criterion = 'entropy') #max_depth=None,min_samples_leaf=1  
dt_model.fit(scaledx_train2,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [0]:
#dt_model.score(x_train_scaled , y_train) 
dt_model.score(scaledx_test2 , y_test)      # performance on test data, y_train)

0.6943333333333334

3. KNN Classifier

In [0]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [0]:
sc=StandardScaler()
sc.fit(x_train2)
scaledx_train2 = sc.transform(x_train2)
scaledx_test2 = sc.transform(x_test2)

In [0]:
#k=3
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train2,y_train)
print("Testing Accuracy")
print(knn.score(x_test2,y_test))
print("Training Accuracy")
print(knn.score(x_train2,y_train))
#predicted = knn.predict(scaledx_test2)

Testing Accuracy
0.4838877338877339
Training Accuracy
0.7282651072124756


In [0]:
#k=3
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train2,y_train)
print("Testing Accuracy")
print(knn.score(x_test2,y_test))
print("Training Accuracy")
print(knn.score(x_train2,y_train))
predicted = knn.predict(x_test2)

Testing Accuracy
0.4696666666666667
Training Accuracy
0.7407857142857143
